In [1]:
from tt_gutenberg.authors import *

list_authors(by_languages=True, alias=True)

['Grimm, Jacob Ludwig Carl',
 'Grimm, Wilhelm Carl',
 'Alighieri, Dante',
 'Stevenson, R. L. (Robert Louis)',
 "Wilde, Oscar Fingal O'Flahertie Wills",
 'Andersen, Hans Christian',
 'Poe, Edgar Allen',
 'Όμηρος',
 'Dodgson, Charles Lutwidge',
 'Πλάτων',
 'Swift, J. (Jonathan)',
 'Chaney, John Griffith',
 'De Maupassant, Guy',
 'Crayon, Geoffrey',
 'Rollan, R.',
 'Wells, Herbert George',
 'Gloux, Olivier',
 'Descartes, Rene',
 'Von Schmid, Christoph',
 'Darwin, Charles Robert',
 'Erasmus, of Rotterdam',
 'Murger, Henry',
 'Engels, Frederick',
 'Augustine, Saint',
 'Michelet, J.',
 'Strindberg, Johan August',
 'Wallace, Lewis',
 'Mill, J. S. (John Stuart)',
 'Ruskin, J. (John)',
 'Buonarroti, Michelangelo',
 'Racine, Jean Baptiste',
 'Ohnet, Jorge',
 '孔子',
 'Merimee, Prosper',
 'Daudet, Louis Marie Alphonse',
 'Malot, Hector-Henri',
 'Bunyan, Johann',
 'Reuter, Heinrich Ludwig Christian Friedrich',
 'Whitman, Walter',
 'Branch, Stephen',
 'Harte, Francis Bret',
 'Chaucer, Jeffrey',
 'Curwood, James-Oliver',
 'Heine, H. (Heinrich)',
 'Goldsmit, Oliver',
 'Dekker, Eduard Douwes',
 'Collins, William Wilkie',
 'Steiner, Rudolph',
 'Key, Ellen Karolina Sofia',
 'Longfellow, Henry W.',
 'Bazin, Rene',
 'Barnivelt, Esdras',
 'Stevenson, Burton E.',
 'Carlyle, T. (Thomas)',
 'Hawkins, Anthony Hope',
 'Haeckel, Ernst Heinrich Philipp August',
 'Lessing, G. E.',
 'Hauptmann, Gerhart Johann Robert',
 'Diderot, Pantophile',
 'Brown, Giorgio Rossi',
 'Donquichote, Marguerite',
 'Válmíki',
 'Kock, Charles Paul de',
 'Ewald, Karl',
 'Michaelis, Richard C.',
 'Verhaeren, Émile',
 'Warneford, Lieutenant',
 'Storm, Hans Theodor Woldsen',
 'Couperus, Louis Marie Anne',
 'Maranan, Apolinario Mabini y',
 'Keller, Gotfryd',
 'Weyman, Stanley J. (Stanley John)',
 'Wassermann, Jacob',
 'Sardou, V. (Victorien)',
 'Long, William Joseph',
 'Shelley, P. B. (Percy Bysshe)',
 'Verlaine, Paul Marie',
 'Bush, W. (Wilhelm)',
 'Brehm, A. E. (Alfred Edmund)',
 'Jacobsen, Jens Peter',
 'Freitag, Gustav',
 'Campe, J. H. (Joachim Heinrich)',
 'Nodier, Jean Charles Emmanuel',
 'Peltonen, Vihtori',
 'Boethius, Anicius Manlius Severinus',
 'Tennyson, Alfred Lord',
 'Zschokke, Johann Heinrich Daniel',
 'Sallustius Crispus, Gaius',
 'Davis, Frederick Hadland',
 'Norris, Benjamin Franklin',
 'Oksanen, A.',
 'Friis, Jens Andreas',
 'Blanc, H. (Henry)',
 'Forster, Edward Morgan',
 'Pennell, Theodore Leighton',
 'Gjellerup, Karl Adolph',
 'Hull, Edith Maude',
 'Boothby, Guy Newell',
 'Ernst, Otto',
 'Banfield, Edmund James',
 'Wallace, Richard Horatio Edgar',
 'Ritchie, F. (Francis)',
 'Charles, Elisabeth Rundle',
 'Morley, Christopher Darlington',
 'Moisa, Dorin T.',
 'Baruch, Moses',
 'Uzanne, Louis Octave',
 'Robida, A. (Albert)',
 'Ingram, Eleanor Marie',
 'Montalte, Louis de',
 'Lie, Jonas Lauritz Idemil',
 'Shackleton, E. H. (Ernest Henry), Sir',
 'Sewell, Ana',
 'Kafka, F. (Franz)',
 'Young, Artur',
 'Guthrie, Thomas Anstey',
 'Gaboriau, Émile',
 'Raleigh, Sir Walter Alexander',
 'Fletcher, Joseph Smith',
 'Stoker, Abraham',
 'Glyn, Elinor Sutherland',
 'Hemon, Louis',
 'Watson, John',
 'Obama, Barack Hussein, II',
 'Collado, D. (Diego)',
 'Li, Ya-ko',
 'Brillat-Savarin, Jean Anthelme',
 'Wilberforce, W. (William)',
 'Bang, Herman Joachim',
 'Benoit, Pierre',
 'Luska, Sidney',
 'Seignobos, Ch. (Charles)',
 'Ferri, Enrique',
 'Hobson, John Atkinson',
 'Aguinaldo y Famy, Emilio',
 'Falkner, J. Meade (John Meade)',
 'Tweedsmuir, John Buchan, Baron',
 'Edwards, O. M., Sir',
 'Plautus, Marcus Accius',
 'Lonnrot, Elias',
 'Tavaststjerna, Karl A. (Karl August)',
 'Гончаров, Иван Александрович',
 "D'Holbach, Baron",
 'Maspero, Gaston Camille Charles, Sir',
 'Jacobs, William Wymark',
 '谷崎潤一郎',
 'Cotterill, Henry Bernard',
 'Huch, Ricarda Octavia',
 'Jones, Raymond F. (Raymond Fisher)',
 'Smith, Sarah',
 '曹雪芹',
 'Hackluyt, Richard',
 'Lock, John',
 'Urpia, Jaime Luciano Balmes',
 'Caius Julius Phaedrus',
 'Tourgee, Albion Winegar',
 'Jensen, Johannes Vilhelm',
 'Lundegard, Axel',
 'De Wit, Augusta',
 'Dodge, M. E. (Mary Elizabeth)',
 'Mitchell, J. A. (John Ames)',
 'Huizinga, J. (Johan)',
 'Maundeville, John',
 'Yorick, Mr.',
 'Veniero, Lorenzo',
 'Liszt, F. (Franz)',
 'Gasson, Herbert N. (Herbert Newton)',
 'Guerrazzi, F. D. (Francesco Domenico)',
 'Lowell, Edward Jackson',
 'Faraday, M. (Michael)',
 'Tegner, Esaias',
 'Disraeli, B. (Benjamin), Earl of Beaconsfield',
 'Aneurin',
 'Slousch, Nahum',
 'Wedekind, Benjamin Franklin',
 'Lorenc, Frantisek Vladimir',
 'Boyer, A. (Abel)',
 'Junius',
 'Crawford, Francis Marion',
 'Moinaux, J. (Jules)',
 'Goffic, Charles Le',
 'Wyss, J. D. (Johann David)',
 'Valois, Marguerite de',
 'Souvestre, Emile',
 'Lermina, Jules Hippolyte',
 'Menant, Dauphine',
 'Schopfer, Jean',
 'Pegge, S. (Samuel)',
 'Strachey, Giles Lytton',
 'Blanche, August Teodor',
 'Von Liebig, Justus, Freiherr',
 'Cameron, V. L. (Verney Lovett)',
 'Giacosa, G. (Giuseppe)',
 'Fewkes, J. Walter (Jesse Walter)',
 "O'Connor, John Charles",
 'Rebecque, Henri Benjamin Constant de',
 'Eden, Charles Henry',
 'Hegel, G. W. F. (Georg Wilhelm Friedrich)',
 'Woolsey, Sarah Chauncey',
 'Borrow, George Henry',
 'Hayes, Charles Frederic',
 'Huxley, T. H. (Thomas Henry)',
 'Ceynowa, Florian Stanislaw',
 'Delpit, Marc-Adrien',
 'Kroeh, Charles F.',
 'Marcus Vitruvius Pollio',
 'Serner, Gunnar',
 'Carlet, Pierre',
 'Latzko, Adolf Andreas',
 'Polko, E. (Elise)',
 'Ellis, Henry Havelock',
 'Murray, M. A. (Margaret Alice)',
 'Churton Braby, Maud',
 'Stallman, Richard M.',
 'Bougainville, comte de (Louis-Antoine)',
 'Iron, Ralph',
 'Roessler, Erwin William Eugene',
 'Lemonnier, Antoine Louis Camille',
 'Cousin, Vittorio',
 'Planck, Max Karl Ernst Ludwig',
 'Bates, Harriet Leonora Vose',
 'Mallanaga',
 'Mitre, Bartolome',
 'Burckhardt, Jakob Christoph',
 'Bebel, Auguste',
 'Beck, James Montgomery',
 'Sabatini, R.',
 'Finnemore, J. (John)',
 'Lasker, Eduard',
 'Wecksell, Josef Julius',
 'Sinjohn, John',
 'Newton, Sir Isaac',
 'Della Porta, Giambattista',
 'Edwardes, Edward Tickner',
 'Bushnell, Curtis Clark',
 'Δημοσθένης',
 'Chevalier, Michael',
 'Beach, Rex Ellingwood',
 'Schlemihl, Peter',
 'Faccio, Rina',
 'De Gorostiza, Manuel Eduardo',
 'Jagor, Andreas Fedor',
 'Runeberg, J. L. (Johan Ludvig)',
 'Seume, J. G. (Johann Gottfried)',
 'Figuier, Guillaume-Louis',
 'Spence, James Lewis Thomas Chalmers',
 'Kyrburg, Fritz von der',
 'Holmes, Gordon',
 'Topelius, Toini Mathilda',
 'Wells, David A.',
 'Gurdon, Philip Richard Thornhagh',
 'Heer, Jakob Christoph',
 'Linnaeus, Carolus',
 'Pfeiffer, Ida Reyer',
 'Massenet, J. (Jules)',
 'Cherbuliez, Charles Victor',
 'Enochs, James Bryon',
 'Bull, Jakob B.',
 'Gozlan, Leon',
 'Nansen, P. (Peter)',
 'Lemercier, Eugene Emmanuel',
 'Roux, Hugues le',
 'Alcock, D.',
 'Malatesta, Enrico',
 'Wangemann, Eduard Carl Otto',
 'Lindsay, T. M. (Thomas Martin)',
 'Greenfield, Gulielmus',
 'Beyrich, Clementine (Helm), Frau',
 'Ford, Ricardo',
 'Peard, Frances M. (Frances Mary)',
 'Mosso, Angelo',
 'Ostwald, Friedrich Wilhelm',
 'Drago, Luis Maria',
 'Lindman, Voldemar',
 'Vanderem, Fernand',
 'Voß, Richard',
 'Fechner, G. Th. (Gustav Theodor)',
 'Scheepstra, Hendericus',
 'Harting, P. (Pieter)',
 'Junghuhn, F. W.',
 'Busch, Julius Hermann Moritz',
 'Ubaldino, Petruccio',
 'Hemmer, Jarl Robert',
 'Philippe, Ch.-L. (Charles-Louis)',
 'Donner, O. (Otto)',
 'Runa',
 'Ingelius, A. G.',
 'Keller, Helen Adams',
 'Endle, S. (Sidney)',
 'Cairon, Claude Antoine Jules',
 'Jones, Alfred Ernest',
 'Labaigt, Laurent',
 'Urbanus',
 'Bell, Gertrude Margaret Lowthian',
 'Westermarck, Edvard Alexander',
 'Revesz, Bela',
 'Borel, Jean',
 'Anderson, James Drummond',
 'Goose, Mary Susan',
 'Corroyer, Édouard',
 'Loránd, Arnold',
 'Weule, K. (Karl)',
 'Hartmann, F. (Franz)',
 'Paine, Walter Lionel',
 'Mainwaring, C. L.',
 'De Fornaro, Carlo',
 'Morne, Arvid',
 'Birt, Theodorus',
 'Arrhenius, Svante August',
 'Caspari, Karl Heinrich',
 'Hocker, Gustav',
 'Sayer, Geo. J.',
 'Coote, Miss',
 'Crowther, S. (Samuel)',
 'Gunnarsons, Gunnars',
 'Delepierre, Joseph Octave',
 'Rakosi, Viktor',
 'Soderhjelm, Alma',
 'Blommaert, Willem',
 'Papini, G. (Giovanni)',
 'Wilder, Thornton Niven',
 'Bernard, Paul',
 'Kloosterman, Jan Ritskes',
 'Brazil. Commissao, Exposicao internacioncal de borracha de New York, 1912',
 'Fry, Sheila Kaye-Smith',
 'Stedman, Jean-Gabriel',
 'Rollin, Carol',
 'Gubernatis, Angelo de, conte',
 'Pluschow, Gunther',
 'Henley, W. E. (William Ernest)',
 'Edmunds, C. K. (Charles Keyser)',
 'Adam, Graeme Mercer',
 'Clay, H. (Henry)',
 'Calhoun, John Caldwell',
 'Benton, Thomas H. (Thomas Hart)',
 'Baldwin, Edward',
 '金田康正',
 'Gould, George Milbry',
 'Pyle, Walter Lytle',
 'Mercer, Cecil William',
 'Munk, Joseph Amasa',
 'Gilbert, William Schwenck, Sir',
 'Beerbohm, Henry Maximilian, Sir',
 'Merritt, A. (Abraham)',
 '岡倉天心',
 'Talbot, Frederick A.',
 'Fitzgerald, Francis Scott Key',
 'Tolstoy, Ilya, Count',
 'Martin, T. C. (Thomas Commerford)',
 'Blackmore, Richard Doddridge',
 'Weems, Mason Locke',
 'Smith, F. Hopkinson (Francis Hopkinson)',
 'White, Mary',
 'Clatten, Lillian',
 'Christie, Agatha Mary Clarissa Miller',
 'Marsh, William Lockwood',
 'Marion, F. (Fulgence)',
 'Dana, Marvin Hill',
 'Chanute, O. (Octave)',
 'Goffman, Ken',
 'Waters, Mrs. W. G.',
 'Haldeman-Julius, Anna Marcet Haldeman',
 'Kendall, Thomas Henry',
 'Stewart, Calvin Edward',
 'Derry Down Derry',
 'Gordon, I. L. (Irwin Leslie)',
 'Higginson, T. W. (Thomas Wentworth)',
 'Parkman, F. (Francis)',
 'Mackay, Chas. (Charles)',
 'Livingston, David',
 'Society, American Tract',
 'Bishop, Nathaniel Holmes',
 'Grammaticus, Saxo',
 'Brieux, Eugene',
 'Draper, J. W. (John William)',
 'Congrove, Mr. (William)',
 'De Rougemont, Louis',
 'Browne, Thomas Alexander',
 'Herrick, R. (Robert)',
 'Palgrave, Francis T.',
 'Cobb, Irvin Shrewsbury',
 'Tyndal, John',
 'Thompson, James',
 'Aiken, Conrad Potter',
 'Cody, Helen',
 'Green, Olive',
 'Redgrove, Herbert Stanley',
 'Bayly, Ada Ellen',
 'Davis, James John',
 'Gross, Hans Gustav Adolf',
 'Eliot, Thomas Stearns',
 'Addams, Laura Jane',
 'Watson, Helen Brodie Cowan',
 'Murray, Robert Fuller',
 'Waterlow, Sydney Philip Perigal, Sir',
 'Cardozo, Benjamin Nathan',
 'Wallace, D. Mackenzie (Donald Mackenzie)',
 'Bullen, Frank T. (Frank Thomas)',
 'De Bonneville, Benjamin Louis Eulalie',
 'Porter, William Sidney',
 'Ogden Stewart, Donald',
 'Gissing, George Robert',
 'Keene, Henry George',
 'Carvalho, David N. (David Nunes)',
 'Brooks, E. S. (Elbridge Streeter)',
 'Osler, Sir William',
 'McAfee, Cleland B. (Cleland Boyd)',
 'Esse, James',
 'De Rojas, Fernando',
 'Stephenson, Nathaniel Wright',
 'Dau, William Herman Theodore',
 'Bente, Friedrich',
 'Keith, Marian',
 'Raine, William McLeod',
 'Burgess, Thornton Waldo',
 'Wilkinson, Elia',
 'Molloy, Joseph Fitzgerald',
 'Punshon, Ernest Robertson',
 'McClintock, Porter Lander',
 'Cotton, William',
 'Cellarius',
 'Seward, Albert Charles, Sir',
 'Reeve, Arthur Benjamin',
 'Penfeather, Amabel',
 'Bliss, Elizabeth Davis',
 'Giles, John Allen',
 'Severy, Melvin Linwood',
 'Chapin, Edwin Hubbell',
 '芥川龍之介',
 'Huxley, Aldous Leonard',
 'Barrett-Browning, Elizabeth',
 'Ellis, John Breckenridge',
 'King, Leonard William',
 'Dana, R. H. (Richard Henry)',
 'Donn-Byrne, Brian Oswald',
 'Lincoln, Joseph C.',
 'Pinches, Theophilus Goldridge',
 'Smith, William George',
 'Hutton, Joseph Edmund',
 "O'Reilly, Augustine J.",
 'Burke, Sydney Thomas',
 'Barbour, Anna Maynard',
 'Webster, J. (John)',
 'Roe, E. P. (Edward Payson)',
 'Craig, J. H.',
 'Ball, Robert Stawell, Sir',
 'Lee, R. E. (Robert Edward)',
 'Cory, David Magie',
 'Evans, Chris',
 'Childers, Robert Erskine',
 'Palmer, Alice Elvira Freeman',
 'Washington, Booker Taliaferro',
 'Mackail, John William',
 'Dodge, Mary Abigail',
 'Campbell, Margaretta Wade',
 'James, G. Wharton (George Wharton)',
 'Collumb, Patrick',
 'Valentine, Douglas',
 'Hastings, Elizabeth',
 'Bates, H. W. (Henry Walter)',
 'Ross, Edmund Gibson',
 'Flipper, Henry O. (Henry Ossian)',
 'Christophe, Jules Francois',
 'Kane, W. T. (William Terence)',
 'Mitford, Miss',
 'Chamberlain, B. H. (Basil Hall)',
 'Patanjali',
 'Mason, Amelia Ruth Gere',
 'Mulford, Clarence E.',
 'Walker, H. W. (H. Wilfrid)',
 'Wood, William Charles Henry',
 'Sheridan, P. H. (Philip Henry)',
 'Pinkerton, J. (John)',
 'Trenck, Frederic, Baron',
 'Durham, Pap',
 'Dickinson, Emily Elizabeth',
 'Atkinson, Eleanor Stackhouse',
 'Wrong, George M. (George McKinnon)',
 'Howland, Harold Jacobs',
 'Burnham, Clara Louise Root',
 'Bickerstaff, Isaac',
 'Saunders, Margaret Marshall',
 'Gonzales, Don Manoel',
 'Josephus, Titus Flavius',
 'Allen, E. A. (Emory Adams)',
 'Lidgate, John',
 'Houghton, Carolyn Wells',
 'Fleming, Walter Lynwood',
 'Buck, Solon Justus',
 'French, Alice',
 'Ferguson, William Blair Morton',
 'Fink, Janis Eddy',
 'Emerson, Willis G. (Willis George)',
 'Frost, Robert Lee',
 'Hale, Lucretia Peabody',
 'Shepherd, William Robert',
 'Huntington, E. (Ellsworth)',
 'Skinner, Constance L. (Constance Lindsay)',
 'Paine, Ralph D. (Ralph Delahaye)',
 'Thebaud, Augustus J.',
 'Barry, John Daniel',
 'Neilson, W. A. (William Allan)',
 'Taylor, Thomas Proclus',
 'Tombo, Rudolph',
 'Gift Book Committee of The Militia of Mercy',
 'Wheeler, Ella',
 'Pyle, Katherine',
 'Gordon, Charles William',
 'Stead, Robert James Campbell',
 'Browne, Charles Farrar',
 'Speke, J. H. (John Hanning)',
 'Corwin, Edward S. (Edward Samuel)',
 'Sewell, R. (Robert)',
 'Paes, Domingo',
 'Stoddard, C. W. (Charles Warren)',
 'Moore, Joseph Hampton',
 'Liljencrantz, Ottilie Adelina',
 'Biggs, Walter',
 'Haies, Edward',
 'Stanhope, Philip Dormer, Earl of Chesterfield',
 'Bryce, Viscount',
 'Francis Leggett and Company',
 'Tyrrell, Charles A. (Charles Alfred)',
 'Glover, Mary Baker',
 'Collins, Tom',
 'Walpole, Sir Hugh',
 'Ward, Elizabeth Rebecca',
 'Fitch, Lucy',
 'Leacock, Stephen Butler',
 'Raffaello, Carboni',
 'Field, Edward Salisbury',
 'Ray, Fan',
 'Manners, John Hartley',
 'Ward, A. W., Sir',
 'Cooper, Fridericus Taber',
 'Mackenzie, A. (Alexander)',
 'Bamford, Mary Ellen',
 'Harris, James Thomas',
 'Quin, Dan',
 'Ives, Charles Edward',
 'Williams, R. P. (Rufus Phillips)',
 'Poland, A. B. (Addison B.)',
 'Conway, M. D. (Moncure Daniel)',
 'United States President (1889-1893)',
 'Krehbiel, H. E. (Henry Edward)',
 'Howard-Smith, Logan',
 'James, George Payne Rainsford',
 'Inchbald, Elizabeth Simpson',
 'Fisher, Joseph, the younger, of Youghal',
 'Patterson, John Henry',
 'Gilbert, Clinton Wallace',
 'Becke, George Louis',
 'Turner, F. J. (Frederick Jackson)',
 'Carey, R. Nouchette (Rosa Nouchette)',
 'Landor, Savagius',
 'Patmore, Coventry Kersey Dighton',
 'Ozaki, Yukio, Madame',
 'Chellini, Benvenuto',
 'Thomas, John Jacob',
 'Froude, J. A. (James Anthony)',
 'Weston, Jessie Laidlay',
 'C. S. C.',
 'Lane, Franklin Knight',
 'Colby, Charles William',
 'Cross, Ada Cambridge',
 'Malthus, Thomas Robert',
 'Morris, J. E. (Joseph Ernest)',
 'Fox, C. J. (Charles James)',
 'Haley, Bartley',
 'Saltus, Edgar Evertson',
 'Pearson, E. L. (Edmund Lester)',
 'Mabie, Hamilton W. (Hamilton Wright)',
 'Keble, J. (John)',
 'Lindlahr, H. (Henry)',
 'Haddock, Frank Channing',
 'Hartmann, Henry August George',
 'Tilden, John Henry',
 'Dellenbaugh, Frederick S.',
 'Clontz, Jerry',
 'Hoenshel, Elmer Ulysses',
 'McMurry, Lida Brown',
 'Muir, John Ramsey Bryce',
 'Stone, Jean Mary',
 'Allen, Charles Grant Blairfindie',
 'Newte, Horace Wykeham Can',
 'Sutro, Alfredo',
 'Nogent, Guibert de',
 'Marquis, T. G. (Thomas Guthrie)',
 'Tarbell, Frank Bigelow',
 'Gribbon, William Lancaster',
 'Jardine, Francis Lascelles',
 'Sheldon, Charles Monroe',
 'Berkley, George',
 'Symonds, J. A. (John Addington)',
 'Bury, John Bagnell',
 'Renard, Pierre Jules',
 'Fraser, Mrs. C. F.',
 '羅貫中',
 'Ackland, Thomas Suter',
 'Beasley, Thomas Dykes',
 'Woolley, Lell Hawley',
 'Davis, John F. (John Francis)',
 "O'Meara, J. (James)",
 'Bailey, Almira',
 'Bradley, Edward',
 'Abbott, L.A.',
 'Bradley, Glenn Danford',
 'Davis, W. S. (William Stearns)',
 'Richardson, John',
 'Dennis, Clarence James',
 'Mason, Alfred Edward Woodley',
 'Jordan, D. S. (David Starr)',
 'Wright, Jacob William',
 'Platz, Josephine Lawrence',
 'Franck, Harry A.',
 'Bird, Henry Edward',
 'Baron, Michel',
 'Crockett, Samuel Rutherford',
 'Flindt, Homer Eon',
 'Widtsoe, John A. (John Andreas)',
 'Huneker, James Gibbons',
 'Emerson, C. Wesley (Charles Wesley)',
 'Bach, J. S. (Johann Sebastian)',
 'Abbot, Belle K. (Belle Kendrick)',
 'Conn, Herbert William',
 'Giles, William Ernest Powell',
 'Molera, Eusebius Joseph',
 'Andrews, Christopher Columbus',
 'Cameron, John, soccer player',
 'Galbraith, Anna Mary',
 'Patchin, Frank Glines',
 'Fabian, Warner',
 'United States President (1801-1809)',
 'United States President (1817-1825)',
 'United States President (1841-1845)',
 'United States President (1849-1850)',
 'United States President (1853-1857)',
 'United States President (1857-1861)',
 'United States President (1865-1869)',
 'United States President (1897-1901)',
 'United States President (1945-1953)',
 'United States President (2001-2009)',
 'Skinner, Ada Maria',
 'Cutting, Mary Stewart Doubleday',
 'Wyatt, Edith Franklin',
 'Gatty, Margaret Scott',
 'Mackenzie, H. (Henry)',
 'Shute, Henry Augustus',
 'Clouston, Joseph Storer',
 'Stevens, T. (Thomas)',
 'Yeats, William Butler',
 'Trollope, T. Adolphus (Thomas Adolphus)',
 'Reeves, Clara',
 'Wright, Almroth Edward, Sir',
 'Brahms, J. (Johannes)',
 'Matz, Bertram Waldrom',
 'Murphy, H. C. (Henry Cruse)',
 'Richards, Laura E.',
 'Cherubini, E. (Eugenio)',
 'Wong, L. M.',
 'Drannan, W. F. (William F.)',
 'King, Franklin Hiram',
 "M'Carthy, Justin",
 'Boyd, Andrew Kennedy Hutchinson',
 'Hillyer, Robert Silliman',
 'Remick, Grace M.',
 'Darwin, Sir Francis',
 'Sherlock, Bishop (Thomas)',
 'Gibran, Khalil',
 'Schubert, Franz Peter',
 'Talmage, James Edward',
 'White, W. A. (William Allen)',
 'Morris, Charles Eugene',
 'Woodbury, Mrs. C. J.',
 'Leahy, A. H. (Arthur Herbert)',
 'Turner, Alice',
 'Osmer, W. (William)',
 'Marshall, Henrietta Elizabeth',
 'Kyne, Peter Bernard',
 'Hewlett, Maurice Henry',
 'Ivens, Walter George',
 'Sylvester, Charles H.',
 'Slick, Sam',
 'Keyhoe, Donald Edward',
 'Jones, Steven Earl',
 'Barse, Mary Emma Salisbury',
 'Kingsley, Mary H.',
 'Macaulay, Fannie Caldwell',
 'Lubienski, Maciej',
 'Roy, Lillian Elizabeth Becker',
 'Savage, Richard Henry',
 'Marsh, G. P. (George Perkins)',
 'Kid, Thomas',
 'Harben, William Nathaniel',
 'Hay, John Milton',
 'McGlashan, Charles Fayette',
 'Mangasarian, Mangasar Mugurditch',
 'McMurry, F. M. (Frank Morton)',
 'Adams, Franklin Pierce',
 'Riis, Jacob August',
 'Chaplin, Ralph Hosea',
 'Mouson, Duglas, Sir',
 'Steel, F. A. (Flora Annie)',
 'Zangwill, I. (Israel)',
 'Fowler, Henry Watson',
 'Fowler, Francis George',
 'Newberry, Fanny E. (Fanny Ellsworth)',
 'Blaine, Captain John',
 'Bing, Ding',
 'Pollard, Albert Frederick',
 'Passos, John Dos',
 'Parker, DeWitt H. (DeWitt Henry)',
 'Davis, Henry William Carless',
 'Goldsmid, Edmund Marsden',
 'McGinnis, Mabel Earl',
 'Tranquillus, Gaius Suetonius',
 'Wilkins, William Henry',
 'Hutchinson, Arthur Stuart-Menteth',
 'Hancock, Harrie Irving',
 'March, Anne',
 'Taylor, F. W. (Frederick Winslow)',
 'Bourinot, J. G. (John George)',
 'Pattee, George Kynett',
 'Hooker, J. D. (Joseph Dalton)',
 'Chenevix, Richard',
 'Barbour, R. H. (Ralph Henry)',
 'Harris, William Shuler',
 'Stendal, Russell Martin',
 'Olmstead, Albert Ten Eyck',
 'Stock, Saint George William Joseph',
 'Ellwood, Charles Abram',
 'Gray, Arthur Herbert',
 'Mackenzie, James Bovell',
 'Famous, Howard B.',
 'Sainte-Foy, Charles',
 'Chittenden, Newton H. (Newton Henry)',
 'Benet, William Rose',
 'Johnson, Theresa',
 'Fulford, Theresa',
 'Skinner, Charles Montgomery',
 'Parker, E. H. (Edward Harper)',
 'Jessopp, A. (Augustus)',
 'Serviss, Garrett P. (Garrett Putman)',
 "McGee, T. D. (Thomas D'Arcy)",
 'Arndt, E. M. (Ernst Moritz)',

In [1]:
from tt_gutenberg.data import get_language_counts

language_counts = get_language_counts()

language_counts.sort_values(
    "language_count",
    ascending=False
).head(10)

      gutenberg_author_id  language_count
191                 216.0              18
58                   65.0              14
106                 116.0              12
53                   60.0              11
123                 136.0               9
514                 586.0               9
830                 971.0               9
831                 972.0               9
1920               2298.0               8
46                   53.0               8

In [2]:
from tt_gutenberg.data import get_authors, get_metadata, get_languages

authors = get_authors()
metadata = get_metadata()
languages = get_languages()

authors.head()

,gutenberg_author_id,author,alias,birthdate,deathdate,wikipedia,aliases
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.
1,3,"Lincoln, Abraham",NaN,1809.0,1865.0,https://en.wikipedia.org/wiki/Abraham_Lincoln,"United States President (1861-1865)/Lincoln, Abe"
2,4,"Henry, Patrick",NaN,1736.0,1799.0,https://en.wikipedia.org/wiki/Patrick_Henry,NaN
3,5,"Adam, Paul",NaN,1849.0,1931.0,https://de.wikipedia.org/wiki/Paul_Adam_(Buchb...,NaN
4,7,"Carroll, Lewis","Dodgson, Charles Lutwidge",1832.0,1898.0,https://en.wikipedia.org/wiki/Lewis_Carroll,"Dodgson, Charles Lutwidge"

In [1]:
!conda env list

# conda environments:
#
base                   C:\Users\bandi\anaconda3
h501-gutenberg       * C:\Users\bandi\anaconda3\envs\h501-gutenberg